package com.liurq.teacher.modules.files.mapper;

import com.liurq.teacher.modules.files.entity.rsp.GetFilesListRsp;
import com.liurq.teacher.modules.files.model.FileRecordAdmin;
import com.liurq.teacher.modules.files.model.FileRecordAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileRecordAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    int countByExample(FileRecordAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    int deleteByExample(FileRecordAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    int insert(FileRecordAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    int insertSelective(FileRecordAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    List<FileRecordAdmin> selectByExample(FileRecordAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    FileRecordAdmin selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") FileRecordAdmin record, @Param("example") FileRecordAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    int updateByExample(@Param("record") FileRecordAdmin record, @Param("example") FileRecordAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    int updateByPrimaryKeySelective(FileRecordAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    int updateByPrimaryKey(FileRecordAdmin record);

    /**
     * 查询文件列表
     * @param classId
     * @param eventId
     * @return
     */
    List<GetFilesListRsp> getFilesList(@Param("classId") String classId,@Param("eventId") String eventId,@Param("urlPrefix") String urlPrefix);
}