#mysql数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1i2ivwv45745tt1uo.mysql.rds.aliyuncs.com:3306/teacher_dev?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    password: Lps19980318
    username: buyi
    type: com.alibaba.druid.pool.DruidDataSource
#redis数据源



#日志配置
logging:
  config: classpath:log4j2/log4j2-spring.xml


#mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:com/liurq/modules/**/*.xml
