package com.liurq.student.modules.files.mapper;

import com.liurq.student.modules.files.model.FileRecord;
import com.liurq.student.modules.files.model.FileRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    int countByExample(FileRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    int deleteByExample(FileRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    int insert(FileRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    int insertSelective(FileRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    List<FileRecord> selectByExample(FileRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    FileRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    int updateByExampleSelective(@Param("record") FileRecord record, @Param("example") FileRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    int updateByExample(@Param("record") FileRecord record, @Param("example") FileRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    int updateByPrimaryKeySelective(FileRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_record
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    int updateByPrimaryKey(FileRecord record);
}