package com.liurq.student.modules.files.mapper;

import com.liurq.student.modules.files.model.Parent;
import com.liurq.student.modules.files.model.ParentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int countByExample(ParentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int deleteByExample(ParentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int insert(Parent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int insertSelective(Parent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    List<Parent> selectByExample(ParentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    Parent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int updateByExampleSelective(@Param("record") Parent record, @Param("example") ParentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int updateByExample(@Param("record") Parent record, @Param("example") ParentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int updateByPrimaryKeySelective(Parent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int updateByPrimaryKey(Parent record);
}