package com.liurq.student.modules.files.mapper;

import com.liurq.student.modules.files.model.StudentParent;
import com.liurq.student.modules.files.model.StudentParentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_student_parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int countByExample(StudentParentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_student_parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int deleteByExample(StudentParentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_student_parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_student_parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int insert(StudentParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_student_parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int insertSelective(StudentParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_student_parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    List<StudentParent> selectByExample(StudentParentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_student_parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    StudentParent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_student_parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int updateByExampleSelective(@Param("record") StudentParent record, @Param("example") StudentParentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_student_parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int updateByExample(@Param("record") StudentParent record, @Param("example") StudentParentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_student_parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int updateByPrimaryKeySelective(StudentParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_student_parent
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int updateByPrimaryKey(StudentParent record);
}