package com.liurq.student.modules.files.mapper;

import com.liurq.student.modules.files.model.TeacherClazz;
import com.liurq.student.modules.files.model.TeacherClazzExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeacherClazzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_teacher_clazz
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int countByExample(TeacherClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_teacher_clazz
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int deleteByExample(TeacherClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_teacher_clazz
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_teacher_clazz
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int insert(TeacherClazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_teacher_clazz
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int insertSelective(TeacherClazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_teacher_clazz
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    List<TeacherClazz> selectByExample(TeacherClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_teacher_clazz
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    TeacherClazz selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_teacher_clazz
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int updateByExampleSelective(@Param("record") TeacherClazz record, @Param("example") TeacherClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_teacher_clazz
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int updateByExample(@Param("record") TeacherClazz record, @Param("example") TeacherClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_teacher_clazz
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int updateByPrimaryKeySelective(TeacherClazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tr_teacher_clazz
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    int updateByPrimaryKey(TeacherClazz record);
}