package com.liurq.student.modules.files.model;

import java.util.Date;

public class Clazz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.name
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.location
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.level
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.class_num
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private Integer classNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.id
     *
     * @return the value of clazz.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.id
     *
     * @param id the value for clazz.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.name
     *
     * @return the value of clazz.name
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.name
     *
     * @param name the value for clazz.name
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.location
     *
     * @return the value of clazz.location
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.location
     *
     * @param location the value for clazz.location
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.level
     *
     * @return the value of clazz.level
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.level
     *
     * @param level the value for clazz.level
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.class_num
     *
     * @return the value of clazz.class_num
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public Integer getClassNum() {
        return classNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.class_num
     *
     * @param classNum the value for clazz.class_num
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setClassNum(Integer classNum) {
        this.classNum = classNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.deleted
     *
     * @return the value of clazz.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.deleted
     *
     * @param deleted the value for clazz.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.create_date
     *
     * @return the value of clazz.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.create_date
     *
     * @param createDate the value for clazz.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}