package com.liurq.student.modules.files.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Event {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.title
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.remark
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.start_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.end_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.create_user
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.id
     *
     * @return the value of event.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.id
     *
     * @param id the value for event.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.title
     *
     * @return the value of event.title
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.title
     *
     * @param title the value for event.title
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.remark
     *
     * @return the value of event.remark
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.remark
     *
     * @param remark the value for event.remark
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.start_date
     *
     * @return the value of event.start_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.start_date
     *
     * @param startDate the value for event.start_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.end_date
     *
     * @return the value of event.end_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.end_date
     *
     * @param endDate the value for event.end_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.create_date
     *
     * @return the value of event.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.create_date
     *
     * @param createDate the value for event.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.create_user
     *
     * @return the value of event.create_user
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.create_user
     *
     * @param createUser the value for event.create_user
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.deleted
     *
     * @return the value of event.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.deleted
     *
     * @param deleted the value for event.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }
}