package com.liurq.student.modules.files.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class File implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_name
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.old_name
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String oldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.size
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.type
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.id
     *
     * @return the value of file.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.id
     *
     * @param id the value for file.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_name
     *
     * @return the value of file.file_name
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_name
     *
     * @param fileName the value for file.file_name
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.old_name
     *
     * @return the value of file.old_name
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getOldName() {
        return oldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.old_name
     *
     * @param oldName the value for file.old_name
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setOldName(String oldName) {
        this.oldName = oldName == null ? null : oldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.size
     *
     * @return the value of file.size
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.size
     *
     * @param size the value for file.size
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.type
     *
     * @return the value of file.type
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.type
     *
     * @param type the value for file.type
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.deleted
     *
     * @return the value of file.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.deleted
     *
     * @param deleted the value for file.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.create_date
     *
     * @return the value of file.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.create_date
     *
     * @param createDate the value for file.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}