package com.liurq.student.modules.files.model;

import java.util.Date;

public class Parent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.name
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.sex
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.phone
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.address
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.phone2
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String phone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.relation
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String relation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.bak1
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.bak2
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.bak3
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.bak4
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.bak5
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.bak6
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.bak7
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.bak8
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.bak9
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.id
     *
     * @return the value of parent.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.id
     *
     * @param id the value for parent.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.name
     *
     * @return the value of parent.name
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.name
     *
     * @param name the value for parent.name
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.sex
     *
     * @return the value of parent.sex
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.sex
     *
     * @param sex the value for parent.sex
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.phone
     *
     * @return the value of parent.phone
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.phone
     *
     * @param phone the value for parent.phone
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.address
     *
     * @return the value of parent.address
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.address
     *
     * @param address the value for parent.address
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.phone2
     *
     * @return the value of parent.phone2
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getPhone2() {
        return phone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.phone2
     *
     * @param phone2 the value for parent.phone2
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setPhone2(String phone2) {
        this.phone2 = phone2 == null ? null : phone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.relation
     *
     * @return the value of parent.relation
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.relation
     *
     * @param relation the value for parent.relation
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.bak1
     *
     * @return the value of parent.bak1
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.bak1
     *
     * @param bak1 the value for parent.bak1
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.bak2
     *
     * @return the value of parent.bak2
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.bak2
     *
     * @param bak2 the value for parent.bak2
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.bak3
     *
     * @return the value of parent.bak3
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.bak3
     *
     * @param bak3 the value for parent.bak3
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3 == null ? null : bak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.bak4
     *
     * @return the value of parent.bak4
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak4() {
        return bak4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.bak4
     *
     * @param bak4 the value for parent.bak4
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak4(String bak4) {
        this.bak4 = bak4 == null ? null : bak4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.bak5
     *
     * @return the value of parent.bak5
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak5() {
        return bak5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.bak5
     *
     * @param bak5 the value for parent.bak5
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak5(String bak5) {
        this.bak5 = bak5 == null ? null : bak5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.bak6
     *
     * @return the value of parent.bak6
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak6() {
        return bak6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.bak6
     *
     * @param bak6 the value for parent.bak6
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak6(String bak6) {
        this.bak6 = bak6 == null ? null : bak6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.bak7
     *
     * @return the value of parent.bak7
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak7() {
        return bak7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.bak7
     *
     * @param bak7 the value for parent.bak7
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak7(String bak7) {
        this.bak7 = bak7 == null ? null : bak7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.bak8
     *
     * @return the value of parent.bak8
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak8() {
        return bak8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.bak8
     *
     * @param bak8 the value for parent.bak8
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak8(String bak8) {
        this.bak8 = bak8 == null ? null : bak8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.bak9
     *
     * @return the value of parent.bak9
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak9() {
        return bak9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.bak9
     *
     * @param bak9 the value for parent.bak9
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak9(String bak9) {
        this.bak9 = bak9 == null ? null : bak9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.deleted
     *
     * @return the value of parent.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.deleted
     *
     * @param deleted the value for parent.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.create_date
     *
     * @return the value of parent.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.create_date
     *
     * @param createDate the value for parent.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}