package com.liurq.student.modules.files.model;

import java.util.Date;

public class StudentParent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_student_parent.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_student_parent.student_id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_student_parent.parent_id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_student_parent.relation
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String relation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_student_parent.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_student_parent.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_student_parent.id
     *
     * @return the value of tr_student_parent.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_student_parent.id
     *
     * @param id the value for tr_student_parent.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_student_parent.student_id
     *
     * @return the value of tr_student_parent.student_id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_student_parent.student_id
     *
     * @param studentId the value for tr_student_parent.student_id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_student_parent.parent_id
     *
     * @return the value of tr_student_parent.parent_id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_student_parent.parent_id
     *
     * @param parentId the value for tr_student_parent.parent_id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_student_parent.relation
     *
     * @return the value of tr_student_parent.relation
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_student_parent.relation
     *
     * @param relation the value for tr_student_parent.relation
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_student_parent.deleted
     *
     * @return the value of tr_student_parent.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_student_parent.deleted
     *
     * @param deleted the value for tr_student_parent.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_student_parent.create_date
     *
     * @return the value of tr_student_parent.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_student_parent.create_date
     *
     * @param createDate the value for tr_student_parent.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}