package com.liurq.student.modules.files.model;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.age
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sex
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id_card
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.place_of_domicile
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String placeOfDomicile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.address
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.phone
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.class_id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.bak1
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.bak2
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.bak3
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.bak4
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.bak5
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.bak6
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.bak7
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.bak8
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.bak9
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String bak9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.age
     *
     * @return the value of student.age
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.age
     *
     * @param age the value for student.age
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id_card
     *
     * @return the value of student.id_card
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id_card
     *
     * @param idCard the value for student.id_card
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.place_of_domicile
     *
     * @return the value of student.place_of_domicile
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getPlaceOfDomicile() {
        return placeOfDomicile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.place_of_domicile
     *
     * @param placeOfDomicile the value for student.place_of_domicile
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setPlaceOfDomicile(String placeOfDomicile) {
        this.placeOfDomicile = placeOfDomicile == null ? null : placeOfDomicile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.address
     *
     * @return the value of student.address
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.address
     *
     * @param address the value for student.address
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.phone
     *
     * @return the value of student.phone
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.phone
     *
     * @param phone the value for student.phone
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.class_id
     *
     * @return the value of student.class_id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.class_id
     *
     * @param classId the value for student.class_id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.bak1
     *
     * @return the value of student.bak1
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.bak1
     *
     * @param bak1 the value for student.bak1
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.bak2
     *
     * @return the value of student.bak2
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.bak2
     *
     * @param bak2 the value for student.bak2
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.bak3
     *
     * @return the value of student.bak3
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.bak3
     *
     * @param bak3 the value for student.bak3
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3 == null ? null : bak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.bak4
     *
     * @return the value of student.bak4
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak4() {
        return bak4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.bak4
     *
     * @param bak4 the value for student.bak4
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak4(String bak4) {
        this.bak4 = bak4 == null ? null : bak4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.bak5
     *
     * @return the value of student.bak5
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak5() {
        return bak5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.bak5
     *
     * @param bak5 the value for student.bak5
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak5(String bak5) {
        this.bak5 = bak5 == null ? null : bak5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.bak6
     *
     * @return the value of student.bak6
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak6() {
        return bak6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.bak6
     *
     * @param bak6 the value for student.bak6
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak6(String bak6) {
        this.bak6 = bak6 == null ? null : bak6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.bak7
     *
     * @return the value of student.bak7
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak7() {
        return bak7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.bak7
     *
     * @param bak7 the value for student.bak7
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak7(String bak7) {
        this.bak7 = bak7 == null ? null : bak7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.bak8
     *
     * @return the value of student.bak8
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak8() {
        return bak8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.bak8
     *
     * @param bak8 the value for student.bak8
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak8(String bak8) {
        this.bak8 = bak8 == null ? null : bak8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.bak9
     *
     * @return the value of student.bak9
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getBak9() {
        return bak9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.bak9
     *
     * @param bak9 the value for student.bak9
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setBak9(String bak9) {
        this.bak9 = bak9 == null ? null : bak9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.deleted
     *
     * @return the value of student.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.deleted
     *
     * @param deleted the value for student.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.create_date
     *
     * @return the value of student.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.create_date
     *
     * @param createDate the value for student.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}