package com.liurq.student.modules.files.model;

import java.util.Date;

public class TeacherClazz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_teacher_clazz.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_teacher_clazz.teacher_id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_teacher_clazz.clazz_id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String clazzId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_teacher_clazz.level
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_teacher_clazz.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_teacher_clazz.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_teacher_clazz.id
     *
     * @return the value of tr_teacher_clazz.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_teacher_clazz.id
     *
     * @param id the value for tr_teacher_clazz.id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_teacher_clazz.teacher_id
     *
     * @return the value of tr_teacher_clazz.teacher_id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_teacher_clazz.teacher_id
     *
     * @param teacherId the value for tr_teacher_clazz.teacher_id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_teacher_clazz.clazz_id
     *
     * @return the value of tr_teacher_clazz.clazz_id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getClazzId() {
        return clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_teacher_clazz.clazz_id
     *
     * @param clazzId the value for tr_teacher_clazz.clazz_id
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setClazzId(String clazzId) {
        this.clazzId = clazzId == null ? null : clazzId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_teacher_clazz.level
     *
     * @return the value of tr_teacher_clazz.level
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_teacher_clazz.level
     *
     * @param level the value for tr_teacher_clazz.level
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_teacher_clazz.deleted
     *
     * @return the value of tr_teacher_clazz.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_teacher_clazz.deleted
     *
     * @param deleted the value for tr_teacher_clazz.deleted
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_teacher_clazz.create_date
     *
     * @return the value of tr_teacher_clazz.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_teacher_clazz.create_date
     *
     * @param createDate the value for tr_teacher_clazz.create_date
     *
     * @mbggenerated Mon Sep 20 13:18:35 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}