package com.liurq.student.modules.files.model;

import java.util.Date;

public class TRFileRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_file_record.id
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_file_record.file_id
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_file_record.record_id
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_file_record.deleted
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tr_file_record.create_date
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_file_record.id
     *
     * @return the value of tr_file_record.id
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_file_record.id
     *
     * @param id the value for tr_file_record.id
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_file_record.file_id
     *
     * @return the value of tr_file_record.file_id
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_file_record.file_id
     *
     * @param fileId the value for tr_file_record.file_id
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_file_record.record_id
     *
     * @return the value of tr_file_record.record_id
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_file_record.record_id
     *
     * @param recordId the value for tr_file_record.record_id
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_file_record.deleted
     *
     * @return the value of tr_file_record.deleted
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_file_record.deleted
     *
     * @param deleted the value for tr_file_record.deleted
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tr_file_record.create_date
     *
     * @return the value of tr_file_record.create_date
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tr_file_record.create_date
     *
     * @param createDate the value for tr_file_record.create_date
     *
     * @mbggenerated Mon Sep 20 14:57:26 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}