package com.liurq.teacher.modules.files.model;

import java.util.Date;

public class FileRecordAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.id
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.student_name
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.student_id
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.clazz_id
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    private String clazzId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.clazz_name
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    private String clazzName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.remark
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.deleted
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.create_date
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.bak1
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.bak2
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    private String bak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.bak3
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    private String bak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_record.event_id
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    private String eventId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.id
     *
     * @return the value of file_record.id
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.id
     *
     * @param id the value for file_record.id
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.student_name
     *
     * @return the value of file_record.student_name
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.student_name
     *
     * @param studentName the value for file_record.student_name
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.student_id
     *
     * @return the value of file_record.student_id
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.student_id
     *
     * @param studentId the value for file_record.student_id
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.clazz_id
     *
     * @return the value of file_record.clazz_id
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public String getClazzId() {
        return clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.clazz_id
     *
     * @param clazzId the value for file_record.clazz_id
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public void setClazzId(String clazzId) {
        this.clazzId = clazzId == null ? null : clazzId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.clazz_name
     *
     * @return the value of file_record.clazz_name
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public String getClazzName() {
        return clazzName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.clazz_name
     *
     * @param clazzName the value for file_record.clazz_name
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public void setClazzName(String clazzName) {
        this.clazzName = clazzName == null ? null : clazzName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.remark
     *
     * @return the value of file_record.remark
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.remark
     *
     * @param remark the value for file_record.remark
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.deleted
     *
     * @return the value of file_record.deleted
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.deleted
     *
     * @param deleted the value for file_record.deleted
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.create_date
     *
     * @return the value of file_record.create_date
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.create_date
     *
     * @param createDate the value for file_record.create_date
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.bak1
     *
     * @return the value of file_record.bak1
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.bak1
     *
     * @param bak1 the value for file_record.bak1
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.bak2
     *
     * @return the value of file_record.bak2
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.bak2
     *
     * @param bak2 the value for file_record.bak2
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.bak3
     *
     * @return the value of file_record.bak3
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.bak3
     *
     * @param bak3 the value for file_record.bak3
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3 == null ? null : bak3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_record.event_id
     *
     * @return the value of file_record.event_id
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_record.event_id
     *
     * @param eventId the value for file_record.event_id
     *
     * @mbggenerated Sat Oct 09 15:21:44 CST 2021
     */
    public void setEventId(String eventId) {
        this.eventId = eventId == null ? null : eventId.trim();
    }
}