package com.liurq.teacher.modules.files.model;

public class SysConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.config_id
     *
     * @mbggenerated Sat Oct 09 15:20:27 CST 2021
     */
    private String configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.config_value
     *
     * @mbggenerated Sat Oct 09 15:20:27 CST 2021
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.deleted
     *
     * @mbggenerated Sat Oct 09 15:20:27 CST 2021
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.remark
     *
     * @mbggenerated Sat Oct 09 15:20:27 CST 2021
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.config_id
     *
     * @return the value of sys_config.config_id
     *
     * @mbggenerated Sat Oct 09 15:20:27 CST 2021
     */
    public String getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.config_id
     *
     * @param configId the value for sys_config.config_id
     *
     * @mbggenerated Sat Oct 09 15:20:27 CST 2021
     */
    public void setConfigId(String configId) {
        this.configId = configId == null ? null : configId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.config_value
     *
     * @return the value of sys_config.config_value
     *
     * @mbggenerated Sat Oct 09 15:20:27 CST 2021
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.config_value
     *
     * @param configValue the value for sys_config.config_value
     *
     * @mbggenerated Sat Oct 09 15:20:27 CST 2021
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.deleted
     *
     * @return the value of sys_config.deleted
     *
     * @mbggenerated Sat Oct 09 15:20:27 CST 2021
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.deleted
     *
     * @param deleted the value for sys_config.deleted
     *
     * @mbggenerated Sat Oct 09 15:20:27 CST 2021
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.remark
     *
     * @return the value of sys_config.remark
     *
     * @mbggenerated Sat Oct 09 15:20:27 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.remark
     *
     * @param remark the value for sys_config.remark
     *
     * @mbggenerated Sat Oct 09 15:20:27 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}